### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by jonschlinkert** [transparent/pm#1]
- [ ] topics guidelines
- [ ] GitHub permissions guide and guidelines, for Teams, Collaborators, etc.
- [ ] Code style guides (basic outlines)
- [ ] Cheatsheets 
- [ ] config file templates (`.eslint.json`, `.travis.yml`, `.appveyor.yml`, `.gitignore`, `.editorconfig`, etc)
- [ ] issue label templates
- [ ] contributing templates
